packages:
      - packages/*

catalog:
      'bun': 1.2.18
      'react': 0.0.0-experimental-06e89951-20250620
      'react-dom': 0.0.0-experimental-06e89951-20250620
      '@rslib/core': ^0.11.0

onlyBuiltDependencies:
      - electron
