export { default as flat } from './flat'
export { default as ipc } from './ipc'
export { default as getLang } from './getLang'
export { default as setGlobalAnimation } from './setGlobalAnimation'
export { default as relaunch } from './relaunch'
export { default as clearStorage } from './clearStorage'
export { default as onWheel } from './onWheel'
export { default as conf } from './conf'
export { default as getValuedObject } from './getValuedObject'

export * from './i18n'
export * from './theme'
export * from './is'
export * from './antd'
export * from './conf'
